# code_review_sample.py
# ---------------------------------------------------------------
# PART 4 CODE REVIEW — Read this file carefully, then run it.
#
# Your job: write a structured review in code_review.txt
# covering what works, what could break, code quality issues,
# and one concrete fix with before/after code.
#
# Do NOT edit this file. Review it as-is.
# ---------------------------------------------------------------

import tkinter as tk
from tkinter import messagebox

root = tk.Tk()
root.title("Note Saver")
root.geometry("400x300")
root.configure(bg="#f0f0f0")

notes = []

def b():
    x = e.get()
    notes.append(x)
    lb.insert(tk.END, x)
    e.delete(0, tk.END)

def d():
    i = lb.curselection()
    lb.delete(i)
    notes.pop(i[0])

def sv():
    f = open("notes.txt", "w")
    for n in notes:
        f.write(n)
    f.close()
    messagebox.showinfo("ok", "ok")

# UI
tk.Label(root, text="notes app", bg="#f0f0f0", fg="#dddddd", font=("Arial", 18)).pack(pady=5)

e = tk.Entry(root, width=40, bg="#ffffff", fg="#000000")
e.pack(pady=3)

tk.Button(root, text="add", command=b, bg="#e0e0e0").pack()

lb = tk.Listbox(root, width=45, height=7, bg="#ffffff")
lb.pack(pady=5)

frame = tk.Frame(root, bg="#f0f0f0")
frame.pack()
tk.Button(frame, text="delete", command=d, bg="#e0e0e0").pack(side="left", padx=3)
tk.Button(frame, text="save", command=sv, bg="#e0e0e0").pack(side="left", padx=3)

root.mainloop()
